# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TM_Socket' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'CocoaAsyncSocket'


  target 'TM_SocketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TM_SocketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
