# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TM_Scoket  服务器' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TM_Scoket  服务器
pod 'CocoaAsyncSocket'

  target 'TM_Scoket  服务器Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TM_Scoket  服务器UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
